version: '3'

services:
  db:
    image: mysql:8.0
    container_name: myjob-db-container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/myjob_db.sql:/docker-entrypoint-initdb.d/data.sql
      - myjob-volume:/var/lib/mysql
    networks:
      - myjob-network
    ports:
      - "3307:3306"
    expose:
      - 3006
  redis:
    image: redis:alpine
    container_name: myjob-redis
    restart: unless-stopped
    networks:
      - myjob-network
    ports:
      - "6379:6379"
  backend:
    image: myjob-backend
    container_name: myjob-backend-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    networks:
      - myjob-network
    volumes:
      - ./:/myjob_api
    ports:
      - "8001:8000"
    expose:
      - 8000
    depends_on:
      - db
      - redis
  celery-worker:
    image: myjob-backend
    container_name: myjob-celery-worker
    restart: unless-stopped
    command: celery -A myjob_api.celery worker --loglevel=info
    env_file:
      - .env
    networks:
      - myjob-network
    depends_on:
      - redis
      - backend

networks:
  myjob-network:
    name: myjob-network

volumes:
  myjob-volume: