# Generated by Django 4.1.6 on 2023-05-26 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_mobile_url', models.URLField(blank=True, null=True)),
                ('button_text', models.TextField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('is_show_button', models.BooleanField(default=False)),
                ('description_location', models.IntegerField(choices=[(1, 'TOP_LEFT'), (2, 'TOP_RIGHT'), (3, 'BOTTOM_LEFT'), (4, 'BOTTOM_RIGHT')], default=3)),
                ('platform', models.CharField(choices=[('WEB', 'Website'), ('APP', 'Ứng dụng')], default=1, max_length=3)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'myjob_myjob_banner',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=500)),
                ('rating', models.SmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myjob_myjob_feedback',
            },
        ),
    ]
