# Generated by Django 4.2.3 on 2025-03-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_career_icon_url_career_icon'),
        ('myjob', '0002_banner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_mobile_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image', to='common.file'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image_mobile', to='common.file'),
        ),
    ]
