# Generated by Django 4.1.6 on 2023-04-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0002_notification_usernotification_notification_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
