# Generated by Django 4.1.6 on 2023-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='app_icon_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
