# Generated by Django 4.1.6 on 2023-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='icon_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
