# Generated by Django 4.1.6 on 2023-03-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_advancedskill_remove_jobseekerprofile_skills_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
