# Generated by Django 4.2.3 on 2025-03-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_career_app_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('format', models.CharField(max_length=50)),
                ('resource_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('raw', 'Raw File')], max_length=50)),
                ('uploaded_at', models.DateTimeField()),
                ('bytes', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-create_at'],
            },
        ),
    ]
