# Generated by Django 4.2.3 on 2025-03-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='myjob_files',
        ),
    ]
