# Generated by Django 4.1.6 on 2023-03-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='myjob_common_feedback',
        ),
    ]
