# Generated by Django 4.2.3 on 2025-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_file_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
