# Generated by Django 4.1.6 on 2023-03-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_feedback_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
