# Generated by Django 4.2.3 on 2025-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_file_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='public_id',
            field=models.CharField(max_length=255),
        ),
    ]
