# Generated by Django 4.2.3 on 2025-03-11 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_file_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='career',
            name='icon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file'),
        ),
    ]
