# Generated by Django 4.2.3 on 2025-04-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_career_icon_url_career_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='bytes',
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('AVATAR', 'Avatar'), ('CV', 'CV'), ('LOGO', 'Logo'), ('COVER_IMAGE', 'Cover Image'), ('COMPANY_IMAGE', 'Company Image'), ('CAREER_IMAGE', 'Career Image'), ('WEB_BANNER', 'Web Banner'), ('MOBILE_BANNER', 'Mobile Banner'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='other', max_length=50),
        ),
    ]
