# Generated by Django 4.2.20 on 2025-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_file_bytes_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('AVATAR', 'Avatar'), ('CV', 'CV'), ('LOGO', 'Logo'), ('COVER_IMAGE', 'Cover Image'), ('COMPANY_IMAGE', 'Company Image'), ('CAREER_IMAGE', 'Career Image'), ('WEB_BANNER', 'Web Banner'), ('MOBILE_BANNER', 'Mobile Banner'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
