# Generated by Django 4.1.6 on 2023-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('avatar_url', models.URLField(default='https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80', max_length=300)),
                ('email_notification_active', models.BooleanField(default=True)),
                ('sms_notification_active', models.BooleanField(default=True)),
                ('has_company', models.BooleanField(default=False)),
                ('is_verify_email', models.BooleanField(default=False)),
                ('role_name', models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('EMPLOYER', 'Nhà tuyển dụng'), ('JOB_SEEKER', 'Người tìm việc')], default='JOB_SEEKER', max_length=10)),
            ],
            options={
                'db_table': 'myjob_authentication_user',
            },
        ),
    ]
