# Generated by Django 4.1.6 on 2023-02-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('avatar_url', models.URLField(default='https://cloudinary.com/console/c-7145a9883ab06f170cab39cb3463a5/media_library/folders/c16d59372d09573f486adb6bf8d49e1cb3 ', max_length=300)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True)),
                ('email_notification_active', models.BooleanField(default=True)),
                ('sms_notification_active', models.BooleanField(default=True)),
                ('has_company', models.BooleanField(default=False)),
                ('roles', models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('EMPLOYER', 'Nhà tuyển dụng'), ('JOB_SEEKER', 'Người tìm việc')], default='JOB_SEEKER', max_length=10)),
            ],
            options={
                'db_table': 'myjob_authentication_user',
            },
        ),
    ]
