# Generated by Django 4.1.6 on 2023-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='https://res.cloudinary.com/dtnpj540t/image/upload/v1680550408/my-job/images_default/avatar_default.jpg', max_length=300),
        ),
    ]
