# Generated by Django 4.1.6 on 2023-02-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
