# Generated by Django 4.1.6 on 2023-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_public_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
