# Generated by Django 4.1.6 on 2023-03-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_avatar_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
