# Generated by Django 4.1.6 on 2023-04-22 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('code', models.IntegerField(null=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_password_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myjob_authentication_forgot_password_token',
            },
        ),
    ]
