# Generated by Django 4.1.6 on 2023-04-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_forgotpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
