# Generated by Django 4.1.6 on 2023-04-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_forgotpasswordtoken_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordtoken',
            name='platform',
            field=models.CharField(choices=[('WEB', 'Website'), ('APP', 'Ứng dụng')], default='WEB', max_length=3),
        ),
    ]
