# Generated by Django 4.1.6 on 2023-04-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_forgotpasswordtoken_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
