# Generated by Django 4.1.6 on 2023-03-13 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_image_url', models.URLField(default='https://cloudinary.com/console/c-7145a9883ab06f170cab39cb3463a5/media_library/folders/c16d59372d09573f486adb6bf8d49e1cb3 ')),
                ('companyEmail', models.EmailField(max_length=100, unique=True)),
                ('companyPhone', models.CharField(max_length=15, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=300, null=True)),
                ('tax_code', models.CharField(max_length=30, unique=True)),
                ('since', models.DateField(null=True)),
                ('field_operation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_size', models.SmallIntegerField(choices=[(1, '1-9 nhân viên'), (2, '10-24 nhân viên'), (3, '25-99 nhân viên'), (4, '100-499 nhân viên'), (5, '500-1000 nhân viên'), (6, '1000+ nhân viên'), (7, '5000+ nhân viên'), (8, '10000+ nhân viên')], null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='common.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='common.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myjob_info_company',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('cover_image_url', models.URLField(default='https://img.freepik.com/free-vector/abstract-banner-with-low-poly-connections-design_1048-13077.jpg?w=1800&t=st=1678203802~exp=1678204402~hmac=7661583ba3279862674922af1193b8023fda9b1c08a34b9d756ee92a08238f5f', max_length=300)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True)),
                ('marital_status', models.CharField(choices=[('S', 'Độc thân'), ('M', 'Đã kết hôn')], default='S', max_length=1, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_profiles', to='common.career')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_profiles', to='common.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_profiles', to='common.district')),
            ],
            options={
                'db_table': 'myjob_info_job_seeker_profile',
            },
        ),
        migrations.CreateModel(
            name='SeekerProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile_skills', to='info.jobseekerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile_skills', to='common.skill')),
            ],
            options={
                'db_table': 'myjob_info_seeker_profile_skill',
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('language', models.SmallIntegerField(choices=[(1, 'Việt Nam'), (2, 'Anh'), (3, 'Pháp'), (4, 'Đức'), (5, 'Nga'), (6, 'Trung Quốc'), (7, 'Hàn Quốc'), (8, 'Nhật Bản'), (9, 'Khác')])),
                ('first_language', models.BooleanField(default=False)),
                ('level', models.SmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')])),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_skills', to='info.jobseekerprofile')),
            ],
            options={
                'db_table': 'myjob_info_language_skill',
            },
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.ManyToManyField(related_name='job_seeker_profiles', through='info.SeekerProfileSkill', to='common.skill'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.SmallIntegerField(verbose_name=((1, 'Sinh viên/Thực tập sinh'), (2, 'Mới tốt nghiệp'), (3, 'Nhân viên'), (4, 'Trưởng nhóm/Giám sát'), (5, 'Quản lý'), (6, 'Phó Giám đốc'), (7, 'Giám đốc'), (8, 'Tổng Giám đốc'), (9, 'Chủ tịch/Phó Chủ tịch')))),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_details', to='info.jobseekerprofile')),
            ],
            options={
                'db_table': 'myjob_info_experience_detail',
            },
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('degree_name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=255)),
                ('training_place_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('completed_date', models.DateField(null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='info.jobseekerprofile')),
            ],
            options={
                'db_table': 'myjob_info_education_detail',
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=300)),
                ('index', models.SmallIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_images', to='info.company')),
            ],
            options={
                'db_table': 'myjob_info_company_image',
            },
        ),
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('award_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=255)),
                ('end_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='info.jobseekerprofile')),
            ],
            options={
                'db_table': 'myjob_info_appreciation',
            },
        ),
    ]
