# Generated by Django 4.1.6 on 2023-02-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.SmallIntegerField(choices=[(1, '')], null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Độc thân'), ('M', 'Đã kết hôn')], default='S', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
