# Generated by Django 4.1.6 on 2023-03-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='salary',
        ),
        migrations.AddField(
            model_name='resume',
            name='salary_max',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='resume',
            name='salary_min',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
