# Generated by Django 4.1.6 on 2023-03-15 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('training_place', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='info.jobseekerprofile')),
            ],
            options={
                'db_table': 'myjob_info_certificate',
            },
        ),
        migrations.DeleteModel(
            name='Appreciation',
        ),
    ]
