# Generated by Django 4.1.6 on 2023-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_cover_image_public_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_image_public_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_cover_image_url',
            field=models.URLField(default='https://img.freepik.com/free-vector/purple-abstract-background_1340-17009.jpg?w=1380&t=st=1680457096~exp=1680457696~hmac=dce6634b13f28ecbe48a8de53421b99783d4b3f9dd4286d6ea2e68176cbfc083'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_image_url',
            field=models.URLField(default='https://img.icons8.com/external-xnimrodx-lineal-gradient-xnimrodx/1x/external-company-town-xnimrodx-lineal-gradient-xnimrodx-4.png'),
        ),
    ]
