# Generated by Django 4.1.6 on 2023-03-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciation',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appreciation',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='update_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='seekerprofileskill',
            name='create_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='seekerprofileskill',
            name='update_at',
            field=models.DateTimeField(),
        ),
    ]
