# Generated by Django 4.1.6 on 2023-03-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_resume_salary_resume_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
