# Generated by Django 4.1.6 on 2023-06-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.resume')),
            ],
            options={
                'verbose_name_plural': 'Contact profiles',
                'db_table': 'myjob_info_contact_profile',
            },
        ),
    ]
