# Generated by Django 4.1.6 on 2023-03-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_certificate_delete_appreciation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageskill',
            name='first_language',
        ),
    ]
