# Generated by Django 4.1.6 on 2023-03-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_languageskill_first_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageskill',
            name='description',
        ),
    ]
