# Generated by Django 4.1.6 on 2023-03-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_resume_file_url_resume_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='public_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
