# Generated by Django 4.1.6 on 2023-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_companyimage_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimage',
            name='image_public_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
