# Generated by Django 4.2.3 on 2025-03-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_file_version'),
        ('info', '0003_contactprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='public_id',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_file', to='common.file'),
        ),
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_image', to='common.file'),
        ),
    ]
