# Generated by Django 4.1.6 on 2023-04-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_companyimage_image_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfollowed',
            name='is_followed',
        ),
    ]
