# Generated by Django 4.2.3 on 2025-03-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_resume_file_url_remove_resume_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='image',
        ),
    ]
