# Generated by Django 4.1.6 on 2023-03-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_languageskill_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.SmallIntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='SeekerProfileSkill',
        ),
        migrations.AddField(
            model_name='advancedskill',
            name='job_seeker_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_skills', to='info.jobseekerprofile'),
        ),
    ]
