# Generated by Django 4.1.6 on 2023-03-28 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0004_resume_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('views', models.BigIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_viewed', to='info.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myjob_info_resume_viewed',
            },
        ),
        migrations.CreateModel(
            name='ResumeSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_saved', to='info.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myjob_info_resume_saved',
            },
        ),
        migrations.CreateModel(
            name='CompanyFollowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_followed', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_followed', to='info.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_followed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myjob_info_company_followed',
            },
        ),
    ]
