# Generated by Django 4.1.6 on 2023-03-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_advancedskill_remove_jobseekerprofile_skills_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advancedskill',
            table='myjob_info_advanced_skill',
        ),
    ]
