# Generated by Django 4.2.3 on 2025-03-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_file_public_id'),
        ('info', '0005_remove_resume_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_cover_image_public_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_cover_image_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_image_public_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_image_url',
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_cover_image', to='common.file'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logo', to='common.file'),
        ),
    ]
