# Generated by Django 4.1.6 on 2023-03-28 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0005_resumeviewed_resumesaved_companyfollowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(related_name='companies_followed', through='info.CompanyFollowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='savers',
            field=models.ManyToManyField(related_name='resumes_saved', through='info.ResumeSaved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='viewers',
            field=models.ManyToManyField(related_name='resumes_viewed', through='info.ResumeViewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyfollowed',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company'),
        ),
        migrations.AlterField(
            model_name='companyfollowed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumesaved',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.resume'),
        ),
        migrations.AlterField(
            model_name='resumesaved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumeviewed',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.resume'),
        ),
        migrations.AlterField(
            model_name='resumeviewed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
