# Generated by Django 4.1.6 on 2023-04-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_companyfollowed_is_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_type',
            field=models.SmallIntegerField(choices=[(1, 'Nhân viên chính thức'), (2, 'Bán thời gian'), (3, 'Thời vụ - Nghề tự do'), (4, 'Thực tập')], null=True),
        ),
    ]
