# Generated by Django 4.1.6 on 2023-03-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_advancedskill_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companyEmail',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyPhone',
            new_name='company_phone',
        ),
    ]
