# Generated by Django 4.1.6 on 2023-03-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_company_followers_resume_savers_resume_viewers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
