# Generated by Django 4.2.3 on 2025-03-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_file_public_id'),
        ('info', '0006_remove_company_company_cover_image_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyimage',
            name='image_public_id',
        ),
        migrations.RemoveField(
            model_name='companyimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='companyimage',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_image', to='common.file'),
        ),
    ]
