# Generated by Django 4.1.6 on 2023-04-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_resume_job_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyfollowed',
            options={'verbose_name_plural': 'Companies followed'},
        ),
        migrations.AlterModelOptions(
            name='resumesaved',
            options={'verbose_name_plural': 'Resumes saved'},
        ),
        migrations.AlterModelOptions(
            name='resumeviewed',
            options={'verbose_name_plural': 'Resumes viewed'},
        ),
    ]
