# Generated by Django 4.2.20 on 2025-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_companyimage_image_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_size',
            field=models.SmallIntegerField(choices=[(1, 'Dưới 10 nhân viên'), (2, '10 - 150 nhân viên'), (3, '150 - 300 nhân viên'), (4, 'Trên 300 nhân viên')], null=True),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='language',
            field=models.SmallIntegerField(choices=[(1, 'Việt Nam'), (2, 'Anh'), (3, 'Nhật Bản'), (4, 'Pháp'), (5, 'Trung Quốc'), (6, 'Nga'), (7, 'Hàn Quốc'), (8, 'Đức'), (9, 'Ý'), (10, 'Ả Rập'), (11, 'Khác')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='academic_level',
            field=models.SmallIntegerField(choices=[(1, 'Trên Đại học'), (2, 'Đại học'), (3, 'Cao đẳng'), (4, 'Trung cấp'), (5, 'Trung học'), (6, 'Chứng chỉ')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_type',
            field=models.SmallIntegerField(choices=[(1, 'Toàn thời gian cố định'), (2, 'Toàn thời gian tạm thời'), (3, 'Bán thời gian cố định'), (4, 'Bán thời gian tạm thời'), (5, 'Theo hợp đồng tư vấn'), (6, 'Thực tập'), (7, 'Khác')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Quản lý cấp cao'), (2, 'Quản lý cấp trung'), (3, 'Quản lý nhóm- giám sát'), (4, 'Chuyên gia'), (5, 'Chuyên viên- nhân viên'), (6, 'Cộng tác viên')], null=True),
        ),
    ]
