# Generated by Django 4.1.6 on 2023-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_company_company_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
