# Generated by Django 4.1.6 on 2023-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_company_options_alter_companyfollowed_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_image_url',
            field=models.URLField(default='https://res.cloudinary.com/dtnpj540t/image/upload/v1682831706/my-job/images_default/company_image_default.png'),
        ),
    ]
