# Generated by Django 4.1.6 on 2023-05-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_company_company_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_cover_image_url',
            field=models.URLField(default='https://res.cloudinary.com/dtnpj540t/image/upload/v1683615297/my-job/images_default/company_cover_image_default.jpg'),
        ),
    ]
