# Generated by Django 4.1.6 on 2023-03-31 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_company_facebook_url_company_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='savers',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='viewers',
        ),
        migrations.RemoveField(
            model_name='resumesaved',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resumeviewed',
            name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='company_savers',
            field=models.ManyToManyField(related_name='resumes_saved', through='info.ResumeSaved', to='info.company'),
        ),
        migrations.AddField(
            model_name='resume',
            name='company_viewers',
            field=models.ManyToManyField(related_name='resumes_viewed', through='info.ResumeViewed', to='info.company'),
        ),
        migrations.AddField(
            model_name='resumesaved',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.company'),
        ),
        migrations.AddField(
            model_name='resumeviewed',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.company'),
        ),
    ]
