# Generated by Django 4.1.6 on 2023-03-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_career_icon_url'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='careers',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='common.career'),
        ),
        migrations.DeleteModel(
            name='JobPostCareer',
        ),
    ]
