# Generated by Django 4.1.6 on 2023-04-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_companyfollowed_is_followed'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.resume'),
        ),
    ]
