# Generated by Django 4.1.6 on 2023-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobpostactivity_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpostactivity',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
