# Generated by Django 4.1.6 on 2023-06-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobpost_benefits_enjoyed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='is_send_email',
            field=models.BooleanField(default=False),
        ),
    ]
