# Generated by Django 4.1.6 on 2023-03-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_jobpost_careers_jobpost_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='shares',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
