# Generated by Django 4.1.6 on 2023-06-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobpostactivity_is_send_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostactivity',
            old_name='is_send_email',
            new_name='is_sent_email',
        ),
    ]
