# Generated by Django 4.1.6 on 2023-04-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobpostactivity_email_jobpostactivity_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Đã liên hệ'), (2, 'Đã test'), (3, 'Đã phỏng vấn'), (4, 'Trúng tuyển'), (5, 'Không trúng tuyển')], null=True),
        ),
    ]
