# Generated by Django 4.1.6 on 2023-04-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobpostactivity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostactivity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Chờ xác nhận'), (2, 'Đã liên hệ'), (3, 'Đã test'), (4, 'Đã phỏng vấn'), (5, 'Trúng tuyển'), (6, 'Không trúng tuyển')], default=1),
        ),
    ]
