# Generated by Django 4.1.6 on 2023-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_is_send_email_jobpostactivity_is_sent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
