# Generated by Django 4.1.6 on 2023-03-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobpost_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='is_active',
            new_name='is_verify',
        ),
    ]
