# Generated by Django 4.1.6 on 2023-03-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_is_active_jobpost_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobpost',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
