# Generated by Django 4.1.6 on 2023-06-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobpostactivity_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.IntegerField(choices=[(1, 'Chờ duyệt'), (2, 'Đã duyệt'), (3, 'Không duyệt')], default=1),
        ),
    ]
