# Generated by Django 4.1.6 on 2023-04-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobpost_job_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpostactivity',
            options={'verbose_name_plural': 'Job posts activity'},
        ),
        migrations.AlterModelOptions(
            name='savedjobpost',
            options={'verbose_name_plural': 'Saved job posts'},
        ),
    ]
