# Generated by Django 4.1.6 on 2023-03-31 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_savedjobpost_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='peoples_applied',
            field=models.ManyToManyField(related_name='job_posts_activity', through='job.JobPostActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='peoples_saved',
            field=models.ManyToManyField(related_name='saved_job_posts', through='job.SavedJobPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpostactivity',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost'),
        ),
        migrations.AlterField(
            model_name='jobpostactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedjobpost',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost'),
        ),
        migrations.AlterField(
            model_name='savedjobpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
