# Generated by Django 4.1.6 on 2023-06-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='is_verify',
        ),
    ]
