# Generated by Django 4.1.6 on 2023-04-30 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_city_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0007_alter_jobpostactivity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='location',
        ),
        migrations.CreateModel(
            name='JobPostNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=255)),
                ('position', models.SmallIntegerField(choices=[(1, 'Sinh viên/Thực tập sinh'), (2, 'Mới tốt nghiệp'), (3, 'Nhân viên'), (4, 'Trưởng nhóm/Giám sát'), (5, 'Quản lý'), (6, 'Phó Giám đốc'), (7, 'Giám đốc'), (8, 'Tổng Giám đốc'), (9, 'Chủ tịch/Phó Chủ tịch')])),
                ('type_of_workplace', models.SmallIntegerField(choices=[(1, 'Làm việc tại văn phòng'), (2, 'Làm việc kết hợp'), (3, 'Làm việc tại nhà')])),
                ('experience', models.SmallIntegerField(choices=[(1, 'Chưa có kinh nghiệm'), (2, 'Dưới 1 năm kinh nghiệm '), (3, '1 năm kinh nghiệm'), (4, '2 năm kinh nghiệm'), (5, '3 năm kinh nghiệm'), (6, '4 năm kinh nghiệm'), (7, '5 năm kinh nghiệm'), (8, 'Trên 5 năm kinh nghiệm')])),
                ('academic_level', models.SmallIntegerField(choices=[(1, 'Trên Đại học'), (2, 'Đại học'), (3, 'Cao đẳng'), (4, 'Trung cấp'), (5, 'Trung học'), (6, 'Chứng chỉ nghề')])),
                ('job_type', models.SmallIntegerField(choices=[(1, 'Nhân viên chính thức'), (2, 'Bán thời gian'), (3, 'Thời vụ - Nghề tự do'), (4, 'Thực tập')])),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('frequency', models.IntegerField(choices=[(1, 'Mỗi ngày'), (2, '3 Ngày / lần'), (3, '1 Tuần / 1 lần')])),
                ('is_active', models.BooleanField(default=False)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post_notifications', to='common.career')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post_notifications', to='common.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job post notifications',
                'db_table': 'myjob_job_job_post_notification',
            },
        ),
    ]
