# Generated by Django 4.1.6 on 2023-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_jobpost_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.IntegerField(choices=[(1, 'Chờ duyệt'), (2, 'Không duyệt'), (3, 'Đã duyệt')], default=1),
        ),
    ]
