# Generated by Django 4.1.6 on 2023-03-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_jobpost_peoples_applied_jobpost_peoples_saved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjobpost',
            name='is_saved',
        ),
    ]
