# Generated by Django 4.1.6 on 2023-04-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_jobpost_location_jobpostnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostnotification',
            name='academic_level',
        ),
        migrations.RemoveField(
            model_name='jobpostnotification',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobpostnotification',
            name='type_of_workplace',
        ),
    ]
