# Generated by Django 4.2.20 on 2025-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_jobpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='academic_level',
            field=models.SmallIntegerField(choices=[(1, 'Trên Đại học'), (2, 'Đại học'), (3, 'Cao đẳng'), (4, 'Trung cấp'), (5, 'Trung học'), (6, 'Chứng chỉ')]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.SmallIntegerField(choices=[(1, 'Toàn thời gian cố định'), (2, 'Toàn thời gian tạm thời'), (3, 'Bán thời gian cố định'), (4, 'Bán thời gian tạm thời'), (5, 'Theo hợp đồng tư vấn'), (6, 'Thực tập'), (7, 'Khác')]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Quản lý cấp cao'), (2, 'Quản lý cấp trung'), (3, 'Quản lý nhóm- giám sát'), (4, 'Chuyên gia'), (5, 'Chuyên viên- nhân viên'), (6, 'Cộng tác viên')]),
        ),
        migrations.AlterField(
            model_name='jobpostnotification',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Quản lý cấp cao'), (2, 'Quản lý cấp trung'), (3, 'Quản lý nhóm- giám sát'), (4, 'Chuyên gia'), (5, 'Chuyên viên- nhân viên'), (6, 'Cộng tác viên')], null=True),
        ),
    ]
