# Generated by Django 4.1.6 on 2023-04-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_jobpostnotification_academic_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostnotification',
            old_name='salary_max',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='jobpostnotification',
            name='salary_min',
        ),
    ]
