# Generated by Django 4.1.6 on 2023-04-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_rename_salary_max_jobpostnotification_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostnotification',
            name='experience',
            field=models.SmallIntegerField(choices=[(1, 'Chưa có kinh nghiệm'), (2, 'Dưới 1 năm kinh nghiệm '), (3, '1 năm kinh nghiệm'), (4, '2 năm kinh nghiệm'), (5, '3 năm kinh nghiệm'), (6, '4 năm kinh nghiệm'), (7, '5 năm kinh nghiệm'), (8, 'Trên 5 năm kinh nghiệm')], null=True),
        ),
        migrations.AlterField(
            model_name='jobpostnotification',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Sinh viên/Thực tập sinh'), (2, 'Mới tốt nghiệp'), (3, 'Nhân viên'), (4, 'Trưởng nhóm/Giám sát'), (5, 'Quản lý'), (6, 'Phó Giám đốc'), (7, 'Giám đốc'), (8, 'Tổng Giám đốc'), (9, 'Chủ tịch/Phó Chủ tịch')], null=True),
        ),
        migrations.AlterField(
            model_name='jobpostnotification',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
