# Generated by Django 4.1.6 on 2023-04-30 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_city_options'),
        ('job', '0011_alter_jobpostnotification_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='common.location'),
        ),
    ]
